/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.TouristGuest.view;

/**
 *
 * @author Bryan Maisincho Codes ESPE-DCCO
 */
public class Flight extends javax.swing.JFrame {

    /**
     * Creates new form Flight
     */
    public Flight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCode = new javax.swing.JLabel();
        btnDate = new javax.swing.JLabel();
        btnAirportOfOrigin = new javax.swing.JLabel();
        btnDestinationAirport = new javax.swing.JLabel();
        txtFligth_Code = new javax.swing.JTextField();
        txtAirport_Of_Origin = new javax.swing.JTextField();
        txtDestination_Airport = new javax.swing.JTextField();
        btnDepartureTime = new javax.swing.JLabel();
        txtDeparture_Time = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEditadnSave = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnReturn = new javax.swing.JToggleButton();
        btnNext = new javax.swing.JButton();
        btnExit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("FLIGHT SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        btnCode.setText("Code :");
        jPanel1.add(btnCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        btnDate.setText(" Date:");
        jPanel1.add(btnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        btnAirportOfOrigin.setText("AirportOf Origin:");
        jPanel1.add(btnAirportOfOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        btnDestinationAirport.setText("Destination Airport:");
        jPanel1.add(btnDestinationAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(txtFligth_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 160, -1));
        jPanel1.add(txtAirport_Of_Origin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 160, -1));

        txtDestination_Airport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestination_AirportActionPerformed(evt);
            }
        });
        jPanel1.add(txtDestination_Airport, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 160, -1));

        btnDepartureTime.setText("Departure Time:");
        jPanel1.add(btnDepartureTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel1.add(txtDeparture_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 160, -1));

        btnSave.setText("Save");
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        btnEditadnSave.setText("Edit and Save");
        btnEditadnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditadnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditadnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        btnView.setText("View Register");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        btnNext.setText(" Next");
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        btnExit.setText("Exit");
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDestination_AirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestination_AirportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestination_AirportActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEditadnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditadnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditadnSaveActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAirportOfOrigin;
    private javax.swing.JLabel btnCode;
    private javax.swing.JLabel btnDate;
    private javax.swing.JLabel btnDepartureTime;
    private javax.swing.JLabel btnDestinationAirport;
    private javax.swing.JButton btnEditadnSave;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JButton btnNext;
    private javax.swing.JToggleButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAirport_Of_Origin;
    private javax.swing.JTextField txtDeparture_Time;
    private javax.swing.JTextField txtDestination_Airport;
    private javax.swing.JTextField txtFligth_Code;
    // End of variables declaration//GEN-END:variables
}
