/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.TouristGuest.view;

/**
 *
 * @author Bryan Maisincho Codes ESPE-DCCO
 */
public class ViewRegister extends javax.swing.JFrame {

    /**
     * Creates new form ViewRegister
     */
    public ViewRegister() {
        initComponents();
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        View_Register_User = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSearchByFligthtCode = new javax.swing.JLabel();
        btnSearch_For = new javax.swing.JButton();
        btnSee_Everything = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_View_Register = new javax.swing.JTable();
        txtSearch_By_Figth_Code = new javax.swing.JTextField();
        btnTO_Return = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        View_Register_User.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("VIEW REGISTER");
        View_Register_User.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        btnSearchByFligthtCode.setText("Search By Flight Code ");
        View_Register_User.add(btnSearchByFligthtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        btnSearch_For.setText("Search For");
        View_Register_User.add(btnSearch_For, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        btnSee_Everything.setText("See Everything");
        btnSee_Everything.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSee_EverythingActionPerformed(evt);
            }
        });
        View_Register_User.add(btnSee_Everything, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jTable_View_Register.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Date", "Airport Of Origin", "Destination Airport", "Departure Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_View_Register);

        View_Register_User.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 114, 538, 209));

        txtSearch_By_Figth_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch_By_Figth_CodeActionPerformed(evt);
            }
        });
        View_Register_User.add(txtSearch_By_Figth_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 200, -1));

        btnTO_Return.setText("To Return");
        View_Register_User.add(btnTO_Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));
        View_Register_User.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(View_Register_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(View_Register_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearch_By_Figth_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch_By_Figth_CodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch_By_Figth_CodeActionPerformed

    private void btnSee_EverythingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSee_EverythingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSee_EverythingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel View_Register_User;
    private javax.swing.JLabel btnSearchByFligthtCode;
    private javax.swing.JButton btnSearch_For;
    private javax.swing.JButton btnSee_Everything;
    private javax.swing.JButton btnTO_Return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_View_Register;
    private javax.swing.JTextField txtSearch_By_Figth_Code;
    // End of variables declaration//GEN-END:variables
}
